version: "3"

services:
  app:
    container_name: go-pattern-adapter
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    depends_on:
      - redis
      - memcached

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - 6379:6379

  memcached:
    image: "memcached:latest"
    container_name: memcached
    ports:
      - 11211:11211
